import type { Product } from './types'

export const products: Product[] = [
  {
    id: 1,
    title: 'Áo thun cotton cổ tròn',
    description: 'Áo thun mềm, thoáng mát cho trang phục hằng ngày.',
    price: 189000,
    discountPercentage: 10,
    rating: 4.6,
    stock: 28,
    category: 'Thời trang',
    thumbnail: 'https://cdn.dummyjson.com/product-images/1/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/1/1.webp'],
  },
  {
    id: 2,
    title: 'Tai nghe không dây AirBass',
    description: 'Tai nghe Bluetooth nhỏ gọn với hộp sạc tiện dụng.',
    price: 790000,
    discountPercentage: 15,
    rating: 4.8,
    stock: 12,
    category: 'Công nghệ',
    thumbnail: 'https://cdn.dummyjson.com/product-images/101/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/101/1.webp'],
  },
  {
    id: 3,
    title: 'Bình giữ nhiệt 600ml',
    description: 'Giữ nóng và lạnh, phù hợp mang theo khi đi học hoặc đi làm.',
    price: 245000,
    discountPercentage: 5,
    rating: 4.5,
    stock: 35,
    category: 'Gia dụng',
    thumbnail: 'https://cdn.dummyjson.com/product-images/105/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/105/1.webp'],
  },
  {
    id: 4,
    title: 'Balo laptop chống nước',
    description: 'Balo nhiều ngăn, vừa laptop 15 inch và đồ dùng cá nhân.',
    price: 650000,
    discountPercentage: 12,
    rating: 4.7,
    stock: 9,
    category: 'Phụ kiện',
    thumbnail: 'https://cdn.dummyjson.com/product-images/106/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/106/1.webp'],
  },
  {
    id: 5,
    title: 'Kem dưỡng ẩm da mặt',
    description: 'Kết cấu nhẹ, cấp ẩm cho làn da mềm mịn.',
    price: 320000,
    discountPercentage: 8,
    rating: 4.4,
    stock: 20,
    category: 'Chăm sóc cá nhân',
    thumbnail: 'https://cdn.dummyjson.com/product-images/12/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/12/1.webp'],
  },
  {
    id: 6,
    title: 'Đèn bàn học LED',
    description: 'Ánh sáng dịu mắt, có thể điều chỉnh nhiều mức sáng.',
    price: 410000,
    discountPercentage: 0,
    rating: 4.3,
    stock: 16,
    category: 'Nhà cửa',
    thumbnail: 'https://cdn.dummyjson.com/product-images/95/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/95/1.webp'],
  },
  {
    id: 7,
    title: 'Giày thể thao Urban Run',
    description: 'Thiết kế năng động, đế êm cho các hoạt động thường ngày.',
    price: 980000,
    discountPercentage: 20,
    rating: 4.9,
    stock: 7,
    category: 'Giày dép',
    thumbnail: 'https://cdn.dummyjson.com/product-images/59/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/59/1.webp'],
  },
  {
    id: 8,
    title: 'Đồng hồ đeo tay tối giản',
    description: 'Mặt đồng hồ thanh lịch, phù hợp với nhiều phong cách.',
    price: 540000,
    discountPercentage: 10,
    rating: 4.2,
    stock: 14,
    category: 'Phụ kiện',
    thumbnail: 'https://cdn.dummyjson.com/product-images/62/thumbnail.webp',
    images: ['https://cdn.dummyjson.com/product-images/62/1.webp'],
  },
]
